### ISSUE TITLE
Export to ArcGIS Compact Tile Cache from MBTiles?

### ISSUE THREAD

**Issue by DenisCarriere** [consbio/tpkutils#16]
I know this is a lot of work to implement, however you've been able to achieve the "read" capability already. Would it be possible to export to TPK or ArcGIS Compact Tile Cache from an MBTiles?

You've got some good documentation on reading a TPK, would you have references on saving to TPK? (I know it's the inverse, however that can get pretty complicated without documentation or examples).

**Comment by brendan-ward** [comment]
@DenisCarriere I think this is theoretically possible, but I don't have the time or use case for doing so.  Submitting a pull request to implement that would be welcome.

**Comment by DenisCarriere** [comment]
Totally agree, it's a pretty big undertaking. Unfortunately I've moved my efforts to NodeJS and if I do end up implementing this it would be in Javascript, however the logic would be very similar.

Would you recommend any helpful documentation?

Would be nice to have a CLI tool that converts the following:
- TPK => MBTiles / ArcGIS Server Cache
- MBTiles => ArcGIS Server Cache / TPK
- ArcGIS Server Cache => MBTiles / TPK

Feel free to close this issue anytime.

**Comment by brendan-ward** [comment]
Potentially useful docs and other projects for you are in the bottom of the readme in this repo:
https://gdbgeek.wordpress.com/2012/08/09/demystifying-the-esri-compact-cache/

https://github.com/FuZhenn/tiler-arcgis-bundle

**Comment by sharkinsspatial** [comment]
@DenisCarriere This issue appears to be quite old so I'm not sure if it is still relevant to you but here [https://github.com/sharkinsspatial/tiler-arcgis-bundle](https://github.com/sharkinsspatial/tiler-arcgis-bundle) is a version of the above mentioned `tiler-arcgis-bundle` that has been forked and modified to include writing to the compact cache format.  This can be used in conjunction with the tilelive plugin [https://github.com/fuzhenn/tilelive-arcgis](https://github.com/fuzhenn/tilelive-arcgis) to move tiles into the Compact Cache format.  For writing the additional `.tpk` metadata files you can use this [https://github.com/sharkinsspatial/xyz2tpk](https://github.com/sharkinsspatial/xyz2tpk) as a guideline.  This functionality was originally built by me attempting to reverse engineer the Compact Cache format but it appears ESRI has since released a bare bones 'specification' describing the format in more detail [https://github.com/Esri/raster-tiles-compactcache/blob/master/CompactCacheV2.md](https://github.com/Esri/raster-tiles-compactcache/blob/master/CompactCacheV2.md).  It also looks like the original repo author @fuzhen has made some recent updates based on this document so I will need to revisit this project and do some refactoring to support this new Compact Cache format.  Hope this can be of some assistance to you.

**Comment by brendan-ward** [comment]
@sharkinsspatial thanks for following up on this with additional suggestions!  Even though we don't have plans to support tpk => ArcGIS Compact Cache in this project, hopefully the information on this issue will be useful to others wanting to go in that direction.

**Comment by DenisCarriere** [comment]
@sharkinsspatial 👍 Awesome, thanks for the detailed explanation!
