### ISSUE TITLE
The version is reported as 1.0.0 in the metadata

### ISSUE THREAD

**Issue by alexfriant** [consbio/tpkutils#23]
The version in the metadata table of the mbtiles generated by this tool says "1.0.0". I only looked because somebody told me the mbtiles I created for them using this tool didn't work with their app (sartopo). They sent me an example of an mbtiles file that did work in their app, and it says version "1.2" in the metadata table. The 1.0.0 worked with MapBox, so I'm not sure this is an "issue". Didn't know where else to ask, apologies if I chose the wrong forum to ask.

**Comment by brendan-ward** [comment]
@alexfriant `version` is an optional property according to the [specification](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md) which corresponds to the version of the tileset, not the version of the mbtiles spec used.  This means that users can change this to whatever value they want.

Since tile packages do not have a version, this is available as an attribute on the `TPK` object that you can set: https://github.com/consbio/tpkutils/blob/master/tpkutils/__init__.py#L98

Once it is set, it gets written out to the mbtiles file, and should work in other applications.

I don't have this in the command line interface though, is that how you are using this library?  It would be relatively easy to add that as a command line parameter.

**Comment by alexfriant** [comment]
Thanks for explaining that to me. It's not an issue. No need to add any new functionality. I'll close this.
